#ifndef SDR_REMOTE_CONTROL_SCREEN_TYPE_H
#define SDR_REMOTE_CONTROL_SCREEN_TYPE_H

enum SCREEN_TYPE
{
    SCREEN_TYPE_NONE = 0,
    SCREEN_TYPE_NOT_CONNECTED = 1,
    SCREEN_TYPE_CONNECTED = 2,
};

#endif // SDR_REMOTE_CONTROL_SCREEN_TYPE_H
