#ifndef SDR_REMOTE_CONTROL_SCREEN_SIZES_AND_OFFSETS_H
#define SDR_REMOTE_CONTROL_SCREEN_SIZES_AND_OFFSETS_H

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 320

// ST7789 native resolution is 240x320 so we need (for LovyAnn driver) to invert width/height values & rotate
#define DISPLAY_DRIVER_LOVYANN_ILI9488_WIDTH DISPLAY_HEIGHT
#define DISPLAY_DRIVER_LOVYANN_ILI9488_HEIGHT DISPLAY_WIDTH
#define DISPLAY_DRIVER_LOVYANN_ILI9488_ROTATION 3
#define DISPLAY_DRIVER_LOVYANN_ILI9488_ROTATION_MIRROR_FLIP_VERTICAL 1

#endif // SDR_REMOTE_CONTROL_SCREEN_SIZES_AND_OFFSETS_H
