
#ifndef SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H
#define SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H

/*
    NOTE:
    INTERNAL (PRIVATE) WIDGET CONSTANTS HAVE PREFIX "_"
*/

#define _DISPLAY_PADDING 4 // real draw starts/ends contained in this horizontal/vertical (pixel) padding

/* DUAL VFO WIDGET START */

#define _DUAL_VFO_WIDGET_FONT_SIZE 3          // common font size for all VFO fields (index, freq, mode)
#define _DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT 20 // total pixel height for current font size

// frequency step field margins
#define _DUAL_VFO_WIDGET_FREQUENCY_STEP_HORIZONTAL_MARGIN 2 // frequency step indicator horizontal margin
#define _DUAL_VFO_WIDGET_FREQUENCY_STEP_VERTICAL_MARGIN 4   // frequency step indicator vertical margin
#define _DUAL_VFO_WIDGET_FREQUENCY_STEP_WIDTH 16            // vfo frequency step indicator width
#define _DUAL_VFO_WIDGET_FREQUENCY_STEP_HEIGHT 3            // vfo frequency step indicator height

// field offsets
#define _DUAL_VFO_WIDGET_FREQUENCY_X_OFFSET 87                                       // frequency field x offset
#define _DUAL_VFO_WIDGET_MODE_X_OFFSET 419                                           // mode field x offset
#define _DUAL_VFO_WIDGET_FREQUENCY_STEP_X_OFFSET _DUAL_VFO_WIDGET_FREQUENCY_X_OFFSET // frequency step field x offset
#define _DUAL_VFO_WIDGET_PRIMARY_FREQUENCY_STEP_Y_OFFSET _DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + _DUAL_VFO_WIDGET_FREQUENCY_STEP_VERTICAL_MARGIN
#define _DUAL_VFO_WIDGET_SECONDARY_FREQUENCY_STEP_Y_OFFSET _DUAL_VFO_WIDGET_SINGLE_LINE_HEIGHT + _DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + _DUAL_VFO_WIDGET_FREQUENCY_STEP_VERTICAL_MARGIN

// other
#define _DUAL_VFO_WIDGET_SINGLE_LINE_HEIGHT (_DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + _DUAL_VFO_WIDGET_FREQUENCY_STEP_VERTICAL_MARGIN + _DUAL_VFO_WIDGET_FREQUENCY_STEP_HEIGHT + _DUAL_VFO_WIDGET_FREQUENCY_STEP_VERTICAL_MARGIN) // single VFO line (frequency step indicator included) height

// public widget constants
#define DUAL_VFO_WIDGET_WIDTH DISPLAY_WIDTH - (_DISPLAY_PADDING * 2)
#define DUAL_VFO_WIDGET_HEIGHT _DUAL_VFO_WIDGET_SINGLE_LINE_HEIGHT * 2
#define DUAL_VFO_WIDGET_X_OFFSET _DISPLAY_PADDING
#define DUAL_VFO_WIDGET_Y_OFFSET _DISPLAY_PADDING
#define DUAL_VFO_WIDGET_PADDING 1
#define DUAL_VFO_WIDGET_SECONDARY_VFO_Y_OFFSET _DUAL_VFO_WIDGET_SINGLE_LINE_HEIGHT

/* DUAL VFO WIDGET END */

/* SMETER BLOCK START */

#define SMETER_WIDGET_X_OFFSET _DISPLAY_PADDING
#define SMETER_FONT_SIZE 2
#define SMETER_VALUES_LABEL_X_OFFSET 18
#define SMETER_VALUES_LABEL_Y_OFFSET 70

#define SMETER_HIGH_BARS_Y_OFFSET 94
#define SMETER_LOW_BARS_Y_OFFSET SMETER_HIGH_BARS_Y_OFFSET + 4
#define SMETER_BAR_COUNT 38
#define SMETER_BAR_WIDTH 5
#define SMETER_BAR_HORIZONTAL_MARGIN 4
#define SMETER_LOW_BAR_HEIGHT 24
#define SMETER_HIGH_BAR_HEIGHT SMETER_LOW_BAR_HEIGHT + 4
#define SMETER_BARS_X_OFFSET _DISPLAY_PADDING + SMETER_BAR_HORIZONTAL_MARGIN + 1
#define SMETER_BAR_BG_COLOR 0x8410

/* SMETER BLOCK END */

#endif // SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H
