
#ifndef SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H
#define SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H

#define DISPLAY_PADDING 8 // real draw starts at this padding from (0,0)

/* VFO BLOCK START */

#define DUAL_VFO_WIDGET_FONT_SIZE 3           // common font size for all VFO fields (index, freq, mode)
#define DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT 20  // total pixel height for current font size
#define VFO_WIDGETS_X_OFFSET DISPLAY_PADDING  // VFO's x offset
#define VFO_WIDGETS_Y_OFFSET DISPLAY_PADDING  // VFO's y offset
#define DUAL_VFO_WIDGET_FREQUENCY_X_OFFSET 78 // VFO's frequency x offset
#define DUAL_VFO_WIDGET_MODE_X_OFFSET 410     // VFO's mode x offset

#define VFO_WIDGETS_STEP_HORIZONTAL_MARGIN 2                         // frequency step indicator horizontal margin
#define VFO_WIDGETS_STEP_VERTICAL_MARGIN 4                           // frequency step indicator vertical margin
#define VFO_WIDGETS_STEP_WIDTH 16                                    // vfo frequency step indicator width
#define VFO_WIDGETS_STEP_HEIGHT 3                                    // vfo frequency step indicator height
#define VFO_WIDGETS_STEP_X_OFFSET DUAL_VFO_WIDGET_FREQUENCY_X_OFFSET // first vfo step frecuency x offset

#define DUAL_VFO_WIDGET_SINGLE_VFO_TOTAL_HEIGHT (DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + VFO_WIDGETS_STEP_VERTICAL_MARGIN + VFO_WIDGETS_STEP_HEIGHT + VFO_WIDGETS_STEP_VERTICAL_MARGIN) // single VFO line (frequency step indicator included) height

// primary VFO offsets
#define PRIMARY_VFO_WIDGET_X_OFFSET VFO_WIDGETS_X_OFFSET
#define PRIMARY_VFO_WIDGET_Y_OFFSET VFO_WIDGETS_Y_OFFSET
#define PRIMARY_VFO_STEP_Y_OFFSET PRIMARY_VFO_WIDGET_Y_OFFSET + DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + VFO_WIDGETS_STEP_VERTICAL_MARGIN

// secondary VFO offsets
#define SECONDARY_VFO_WIDGET_X_OFFSET VFO_WIDGETS_X_OFFSET
#define SECONDARY_VFO_WIDGET_Y_OFFSET VFO_WIDGETS_Y_OFFSET + DUAL_VFO_WIDGET_SINGLE_VFO_TOTAL_HEIGHT
#define SECONDARY_VFO_STEP_Y_OFFSET SECONDARY_VFO_WIDGET_Y_OFFSET + DUAL_VFO_WIDGET_FONT_PIXEL_HEIGHT + VFO_WIDGETS_STEP_VERTICAL_MARGIN

// dual VFO widget
#define DUAL_VFO_WIDGET_WIDTH DISPLAY_WIDTH - (DISPLAY_PADDING * 2)
#define DUAL_VFO_WIDGET_HEIGHT DUAL_VFO_WIDGET_SINGLE_VFO_TOTAL_HEIGHT * 2
#define DUAL_VFO_WIDGET_X_OFFSET DISPLAY_PADDING
#define DUAL_VFO_WIDGET_Y_OFFSET DISPLAY_PADDING

/* VFO BLOCK END */

/* SMETER BLOCK START */

#define SMETER_WIDGET_X_OFFSET DISPLAY_PADDING
#define SMETER_FONT_SIZE 2
#define SMETER_VALUES_LABEL_X_OFFSET 18
#define SMETER_VALUES_LABEL_Y_OFFSET 70

#define SMETER_HIGH_BARS_Y_OFFSET 94
#define SMETER_LOW_BARS_Y_OFFSET SMETER_HIGH_BARS_Y_OFFSET + 4
#define SMETER_BAR_COUNT 38
#define SMETER_BAR_WIDTH 5
#define SMETER_BAR_HORIZONTAL_MARGIN 4
#define SMETER_LOW_BAR_HEIGHT 24
#define SMETER_HIGH_BAR_HEIGHT SMETER_LOW_BAR_HEIGHT + 4
#define SMETER_BARS_X_OFFSET DISPLAY_PADDING + SMETER_BAR_HORIZONTAL_MARGIN + 1
#define SMETER_BAR_BG_COLOR 0x8410

/* SMETER BLOCK END */

#endif // SDR_REMOTE_CONTROL_LGFX_SCREEN_CONNECTED_DEFINES_H
