#ifndef SDR_REMOTE_CONTROL_COMMON_DEFINES_H
#define SDR_REMOTE_CONTROL_COMMON_DEFINES_H

#define SDR_REMOTE_CONTROL_CURRENT_VERSION "1.0.0"
#define SDR_REMOTE_CONTROL_CURRENT_VERSION_DATE "2024/09/18"

#define SERIAL_DEFAULT_BAUD_RATE 57600
#define SERIAL_TIMEOUT 2000

// custom VFO index labels (VFOA/VFO1 VFOB/VFO2)
#define VFO_PRIMARY_LABEL "VFOA"
#define VFO_SECONDARY_LABEL "VFOB"

#endif // SDR_REMOTE_CONTROL_COMMON_DEFINES_H
