#ifndef SDR_REMOTE_CONTROL_COMMON_DEFINES_H
#define SDR_REMOTE_CONTROL_COMMON_DEFINES_H

#define SDR_REMOTE_CONTROL_CURRENT_VERSION "0.1.0"
#define SDR_REMOTE_CONTROL_CURRENT_VERSION_DATE "2024/11/28"

#define SERIAL_DEFAULT_BAUD_RATE 57600
#define SERIAL_TIMEOUT 2000

// custom VFO index labels (VFOA/VFO1 VFOB/VFO2)
#define VFO_PRIMARY_LABEL "VFOA"
#define VFO_SECONDARY_LABEL "VFOB"

// IARU region (https://www.iaru.org/about-us/organisation-and-history/regions/)
#define IARU_REGION 1

#endif // SDR_REMOTE_CONTROL_COMMON_DEFINES_H
