#ifndef SDR_REMOTE_CONTROL_COMMON_DEFINES_H
#define SDR_REMOTE_CONTROL_COMMON_DEFINES_H

#define SDR_REMOTE_CONTROL_CURRENT_VERSION "1.0.0"
#define SDR_REMOTE_CONTROL_CURRENT_VERSION_DATE "2024/09/18"

#define DEFAULT_SERIAL_SPEED 57600

#endif // SDR_REMOTE_CONTROL_COMMON_DEFINES_H
