#ifndef SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H
#define SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H

#define TOTAL_MENU_BUTTONS 16

#define COLS_PER_PAGE 4
#define ROWS_PER_PAGE 2

#define BUTTONS_PER_PAGE (COLS_PER_PAGE * ROWS_PER_PAGE)

#define TOTAL_MENU_PAGES 2

#endif // SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H