#ifndef SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H
#define SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H

#define TOTAL_MENU_ITEMS 16

#define MENU_ITEMS_COLS_PER_PAGE 4
#define MENU_ITEMS_ROWS_PER_PAGE 2

#define MENU_ITEMS_PER_PAGE (MENU_ITEMS_COLS_PER_PAGE * MENU_ITEMS_ROWS_PER_PAGE)

#define TOTAL_MENU_PAGES 2

enum availableMenuActions
{
    MENU_ACTION_NONE,
    MENU_ACTION_CONTROL_TUNE,
    MENU_ACTION_CONTROL_VOLUME,
    MENU_ACTION_CONTROL_FILTER,
    MENU_ACTION_SETTINGS,
    MENU_ACTION_TOGGLE_ACTIVE_VFO,
    MENU_ACTION_TOGGLE_ACTIVE_VFO_STEP,
    MENU_ACTION_TOGGLE_ACTIVE_VFO_MODE,
    MENU_ACTION_PREVIOUS_PAGE,
    MENU_ACTION_NEXT_PAGE,
    MENU_ACTION_COPY_VFO_A_B,
    MENU_ACTION_COPY_VFO_B_A,
    MENU_ACTION_INCREASE_BAND,
    MENU_ACTION_DECREASE_BAND,
};

#endif // SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H