#ifndef SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H
#define SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H

#define TOTAL_MENU_ITEMS 16

#define MENU_ITEMS_COLS_PER_PAGE 4
#define MENU_ITEMS_ROWS_PER_PAGE 2

#define MENU_ITEMS_PER_PAGE (MENU_ITEMS_COLS_PER_PAGE * MENU_ITEMS_ROWS_PER_PAGE)

#define TOTAL_MENU_PAGES 2

#endif // SDR_REMOTE_CONTROL_MENU_CONFIGURATION_H